syntax enable
set syntax=on
set nobackup
set noswapfile
set noundofile
set nu
set smartindent
set cindent
set foldmethod=marker
set foldlevel=3 
set foldenable
set autowrite
set noeb
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab 

:imap jk <Esc>

map <F5> : call Complie() <CR>

func Complie()
	exec "w"
	exec "!g++ % -o %< -g -Wall -std=c++11"
endfunc

map <F6> : call Run() <CR>

func Run()
	exec "!./%<"
endfunc

map <F9> : call DeBug() <CR>

func DeBug()
	exec "!gdb %<"
endfunc
